### ISSUE TITLE
TypeError: on_train_batch_start() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by BasinChen** [TorchSpatiotemporal/tsl#10]
![image](https://user-images.githubusercontent.com/47102847/190293309-9150af41-a992-4add-8d36-3e07b30fe8b7.png)

**Comment by junekchen** [comment]
I also meet the same error when I run the example/run_imputation.py code.

**Comment by marshka** [comment]
Hi all, sorry for the late reply! we recently updated the code releasing a more stable version (v0.9.0) with substantial changes. We invite you to check out the new code and the new doc! Please let us know if you still encounter this problem. Cheers!

**Comment by javiersgjavi** [comment]
Hello,

I have version v0.9.0 of tsl and I have exactly the same error. What can I do to solve it?

**Comment by marshka** [comment]
Hi, commit 1f55a6d should have fixed your problem. Let us know if this is not the case, thanks for your contribution!

**Comment by javiersgjavi** [comment]
Thank you very much; the problem is resolved. Thank you for the fast reply!
