### ISSUE TITLE
Differences of args in ImputationDataset between tsl-0.1.1 and the latest

### ISSUE THREAD

**Issue by mrluin** [TorchSpatiotemporal/tsl#12]
Hello,

Thanks for your great contribution in neural spatiotemporal data processing community!

I found that some works used the old version of tsl package, i.e. v-0.1.1, and there are some difference on args compared with the latest version. For example, in tsl-0.1.1 there are `training_mask` and `eval_mask` args in class `ImputationDataset`, but in the latest version `training_mask` is discarded, so could you please tell me is there something changes or some mechanism allow us can discard `training_mask`?

Looking forward to your reply, thanks!

**Comment by marshka** [comment]
Hi, 

thanks for your interest in our work! we renamed `training_mask` as `input_mask` to clarify that this mask is associated with the input inside the model. Besides that, you can also control how many additional points are whitened at random during training with the parameter `whiten_prob` in the `Imputer`.

Actually, we should also rename `training_mask` in the `MissingValues` datasets and improve the documentation on this part, thank you for pointing this out! Feel also free to make pull requests should you have improvements to propose.

Best,

Ivan
