### ISSUE TITLE
Method to specify save location of a dataset

### ISSUE THREAD

**Issue by StefanBloemheuvel** [TorchSpatiotemporal/tsl#15]
Hello TSL team,

Is it possible to add the functionality of specifying the save directory of a dataset?
Such as:
```
dataset = MetrLA('current_path or folder')
```
because I am trying to run TSL on an external GPU cluster where I do not have root access/all permissions. Therefore, I think I am getting the following error when trying to run the MetrLA() command:
```
import tsl
import torch
import numpy as np
np.set_printoptions(suppress=True)
print(f"tsl version  : {tsl.__version__}")
print(f"torch version: {torch.__version__}")
from tsl.datasets import MetrLA
dataset = MetrLA(root='data')
```
gives the error:
```
tsl version  : 0.9.0
torch version: 1.10.1+cu111
Segmentation fault (core dumped)
```
which seems to be: "Segmentation fault" means that you tried to access memory that you do not have access to".

Thanks in advance!

**Comment by marshka** [comment]
Hi, the command 
```
dataset = MetrLA(root='data')
```
is the right one to specify the correct data path and works for me. Are you sure that your error raises from that instruction?
