### ISSUE TITLE
error at test : test_example_imputation

### ISSUE THREAD

**Issue by Tianxu-Jia** [TorchSpatiotemporal/tsl#16]
The error message:
FAILED test_example_imputation.py::test_example_imputation - TypeError: on_train_batch_start() takes 3 positional arguments but 4 were given

Can you please fix the error.

Many thanks

**Comment by marshka** [comment]
Hi, please check issue #10, commit https://github.com/TorchSpatiotemporal/tsl/commit/1f55a6d95c7c361b2ce4b661ef4774d44be6fc5c should have fixed the problem.
