### ISSUE TITLE
Error while training the model in the example notebook: a_gentle_introduction_to_tsl.ipynb

### ISSUE THREAD

**Issue by Capitolhill** [TorchSpatiotemporal/tsl#17]
Any suggestions, on how to resolve `TypeError: forward() got an unexpected keyword argument 'return_last_state'`

![tsl_error](https://user-images.githubusercontent.com/24753433/222084987-c1aaff26-92b3-42db-88fe-4ab138d0ce4a.png)

**Comment by marshka** [comment]
Hi, unfortunately the notebook is not updated to the latest version of tsl yet. We will fix the notebook in next days. In the meantime, I suggest you to check one of the example scripts in the `examples` folder, which show how to use the latest version of tsl for forecasting and imputation.

**Comment by Capitolhill** [comment]
> Hi, unfortunately the notebook is not updated to the latest version of tsl yet. We will fix the notebook in next days. In the meantime, I suggest you to check one of the example scripts in the `examples` folder, which show how to use the latest version of tsl for forecasting and imputation.

Thanks for your quick response. I have been working with the example scripts (in the examples folder), and they work fine. Maybe I will close this issue once you fix the notebook!

**Comment by marshka** [comment]
Hi, we just released version 0.9.2 with - among other improvements - an updated version of the notebook. Check it out here:

https://github.com/TorchSpatiotemporal/tsl/blob/main/examples/notebooks/a_gentle_introduction_to_tsl.ipynb
