### ISSUE TITLE
Doubt about Masked Metric's init

### ISSUE THREAD

**Issue by LucaButera** [TorchSpatiotemporal/tsl#20]
In `tsl.metric.torch.metric_base.MaskedMetric.__init__` we have the following [snippet](https://github.com/TorchSpatiotemporal/tsl/blob/22b8046664549a929ba88e9ae49f88e4a72aae78/tsl/metrics/torch/metric_base.py#L68-L71)

```python
if metric_fn is None:
    self.metric_fn = None
else:
    self.metric_fn = partial(metric_fn, **metric_fn_kwargs)
```

Wouldn't this lead to a behavior in which we have an error thrown for passing `metric_fn=None` only upon computing the metric instead that having it thrown upon class construction?
Is this a desired behavior?

**Comment by marshka** [comment]
Hi Luca,

yes, you're right, the metric function shouldn't be optional. We'll change this soon, thanks!
