### ISSUE TITLE
Pandas version

### ISSUE THREAD

**Issue by LaurentBerder** [TorchSpatiotemporal/tsl#21]
Hi,

I'm very interested in the library you've created (kudos on your documentation!), but am working on a platform (Dataiku) that won't let me install any pandas version (restriction is `pandas>=1.3,<1.4`).
Therefore I can't test your library.
Is there an important incompatibility with earlier versions of pandas that forced you to specifically noted `pandas>=1.4` in the requirements?

**Comment by marshka** [comment]
Hi, thanks for your interest in our work! We noted some incompatibilities that forced us to specify this version, mostly related to the functions used to build exogenous variables starting from a DateTimeIndex. Pandas is used to load dataframes for the datasets in

https://github.com/TorchSpatiotemporal/tsl/blob/154cccf6a07c5cc0558569f4faa18928f3755603/tsl/datasets/prototypes/mixin.py#L110

We also need `numpy>1.20.3` for security reasons, this may create conflicts with previous version of pandas. I suggest you to try installing tsl from source changing manually this dependency and see if this breaks something in you pipeline, it may be the case that for the basic usage of pandas in tsl (data loading as DataFrame in the datasets) previous versions are fine as well.

I'm sorry I cannot be more helpful, we are more than happy to receive contributions if you find some improvements in our library!
