### ISSUE TITLE
sensor locations from pems08

### ISSUE THREAD

**Issue by StefanBloemheuvel** [TorchSpatiotemporal/tsl#28]
Hi creators of TSL,

I would like to know the sensor locations of the pems08 dataset, but those are not available.
However, I think if I know which sensors were used, I can find them in the 'master' dataset: https://www.kaggle.com/datasets/liuxu77/largest

Do you have the names of the sensors available somewhere?

Kind regards,

Stefan

**Comment by marshka** [comment]
Hi Stefan, 

the original Pems08 dataset comes from here: https://github.com/wanhuaiyu/ASTGCN/tree/master/data. Only readings and distances between sensors have been reported. Unfortunately, while the sensor IDs are indeed a useful piece of information, we are not able to provide them.

Best,

Ivan

**Comment by StefanBloemheuvel** [comment]
Alright thanks for letting me know!
