### ISSUE TITLE
How to use covariates

### ISSUE THREAD

**Issue by tboussaid** [TorchSpatiotemporal/tsl#41]
Hi,

Thanks for the huge work done into this library.

I am trying to use it for conceiving a physical simulation predictor.
I want to use covariates, but specifically "forecasted" covariates as schematized below.

![image](https://github.com/user-attachments/assets/263d5f5a-bc87-46ba-ba05-f036cd075203)

For such configuration, I would put: window=horizon=288 and stride=1.
But if I want the model to take the 288-ahead covariates as inputs, should I apply a 288-shift to them at the beginning while creating the dataset?

Thank you in advance.

**Comment by steve3nto** [comment]
Hello,

Better to keep the data without applying strange shifts.
The "proper" way is to use the `input_map` arg to define the alignment of your inputs when creating your `SpatiotemporalDataset`
See https://torch-spatiotemporal.readthedocs.io/en/latest/modules/data_pytorch_datasets.html

For your case, you could pass something like:
```python
from tsl.data import HORIZON
input_map = {
        "u": (["forecasts"], HORIZON),
    }
```

I hope this helps!

**Comment by tboussaid** [comment]
Hi @steve3nto,

Thanks for the quick reply.
It is much clearer how to handle it with input_map.

Best.
