### ISSUE TITLE
Time index as inputs in forward

### ISSUE THREAD

**Issue by Viet1004** [TorchSpatiotemporal/tsl#48]
Hello. I'm doing load forecasting, and some algorithms suggest using day and hour indexes as input variables for models since periodicity is quite essential.

I must change the method `__getitem__` in the `SpatioTemporalDataset` class since the return should include the day and hour index. 

Do you have any other suggestions for solving this problem? If not, would you be open to including this feature?

Thank you very much.

Best regards,

Viet

**Comment by andreacini** [comment]
Hi. You can include any covariate you want in a batch. Checkout, eg, the traffic forecasting [example](https://github.com/TorchSpatiotemporal/tsl/blob/main/examples/forecasting/run_traffic_experiment.py) at line 108.

**Comment by Viet1004** [comment]
Hi. Thank you a lot for your suggestion. I intend to use time index to learn the temporal representation similar to Node Embedding (lookup table). Would like to test that and come back if there is any problem.

**Comment by marshka** [comment]
Hi Viet, in our implementation of the [STID model](https://github.com/TorchSpatiotemporal/tsl/blob/main/tsl/nn/models/temporal/stid_model.py) we do something similar to what you're looking for. I suggest you check out lines:
https://github.com/TorchSpatiotemporal/tsl/blob/f9e5081d198cc4e568a41b0ba472fce0f603c61b/tsl/nn/models/temporal/stid_model.py#L62-L67
and
https://github.com/TorchSpatiotemporal/tsl/blob/f9e5081d198cc4e568a41b0ba472fce0f603c61b/tsl/nn/models/temporal/stid_model.py#L130-L139

In this case, `u` is the one-hot encoding of the temporal variables.

**Comment by Viet1004** [comment]
Thank you for your suggestions. That works very well.
