### ISSUE TITLE
Datasets with several channels

### ISSUE THREAD

**Issue by ucsky** [TorchSpatiotemporal/tsl#5]
Hello,

Is there a dataset with multiple channels available in tsl  in the pre-configured one ?

**Comment by marshka** [comment]
Hi Guillaume,

Not for the moment, the only datasets we provide are with a single channel per node. However, the library supports any custom-made dataset with multiple channels.

Cheers,

Ivan

**Comment by ucsky** [comment]
Hi Ivan,

Thanks, I used others variables in AQI to configure an imputation with multiples channels.

Cheers,
Guillaume
