### ISSUE TITLE
Imputation: change number of nodes after training

### ISSUE THREAD

**Issue by ucsky** [TorchSpatiotemporal/tsl#9]
Hello,

Is it possible to change the number of node after training.
For example I have trained an Imputer with 180 channel and 4 nodes.
Can I perform inference with data that have 180 channel and 5 nodes?

**Comment by marshka** [comment]
Hi, the general answer is yes, as generic GNNs can handle varying topologies. This cannot be the case when your model has also node-dependent components, for instance, node identifiers (e.g., [`StaticGraphEmbedding` ](https://github.com/TorchSpatiotemporal/tsl/blob/main/tsl/nn/base/embedding.py#L10) in tsl). In those cases, there are workarounds you can choose (e.g., you can set a maximum number of nodes and then select the identifiers/embeddings of the only nodes you are considering in that forward pass).
